name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install Test dependencies
      run: |
        pip install flake8 pytest
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        cd src
        pylint $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        cd src
        python3 -m unittest test_*.py